"""Added a quiz to the database

Revision ID: 84e1687e1aa2
Revises: fbe44cdd6f41
Create Date: 2023-07-10 23:51:11.958856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e1687e1aa2'
down_revision = 'fbe44cdd6f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
