"""Add start date and deadline date to columns

Revision ID: bc640ba9d0e1
Revises: 27c23af744ba
Create Date: 2023-07-06 11:24:26.676412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc640ba9d0e1'
down_revision = '27c23af744ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('deadline_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('deadline_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
